# Generated by Django 6.0.1 on 2026-01-23 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddonAccount',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('shared', models.IntegerField()),
            ],
            options={
                'db_table': 'addon_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AddonAccountData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(blank=True, max_length=100, null=True)),
                ('money', models.IntegerField()),
                ('owner', models.CharField(blank=True, max_length=46, null=True)),
            ],
            options={
                'db_table': 'addon_account_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AddonInventory',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('shared', models.IntegerField()),
            ],
            options={
                'db_table': 'addon_inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AddonInventoryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
                ('owner', models.CharField(blank=True, max_length=46, null=True)),
            ],
            options={
                'db_table': 'addon_inventory_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthtokenToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'authtoken_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Banking',
            fields=[
                ('identifier', models.CharField(blank=True, max_length=46, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('time', models.BigIntegerField(blank=True, null=True)),
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('balance', models.IntegerField(blank=True, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'banking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=46, null=True)),
                ('sender', models.CharField(max_length=60)),
                ('target_type', models.CharField(max_length=50)),
                ('target', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=255)),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'billing',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CardealerVehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'cardealer_vehicles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Datastore',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=100)),
                ('shared', models.IntegerField()),
            ],
            options={
                'db_table': 'datastore',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DatastoreData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('owner', models.CharField(blank=True, max_length=46, null=True)),
                ('data', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'datastore_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FineTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('category', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fine_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HouseDecorations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(blank=True, max_length=50, null=True)),
                ('creator', models.CharField(max_length=70)),
                ('modelname', models.CharField(db_column='modelName', max_length=50)),
                ('coords', models.TextField(blank=True, null=True)),
                ('rotation', models.TextField()),
                ('instash', models.IntegerField(db_column='inStash')),
                ('inhouse', models.PositiveIntegerField(db_column='inHouse')),
                ('uniq', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('lightdata', models.TextField(blank=True, db_column='lightData', null=True)),
            ],
            options={
                'db_table': 'house_decorations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Houselocations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('coords', models.TextField(blank=True, null=True)),
                ('owned', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('defaultprice', models.IntegerField(blank=True, db_column='defaultPrice', null=True)),
                ('tier', models.SmallIntegerField(blank=True, null=True)),
                ('garage', models.TextField(blank=True, null=True)),
                ('garageshell', models.TextField(blank=True, db_column='garageShell', null=True)),
                ('creator', models.CharField(blank=True, max_length=50, null=True)),
                ('mlo', models.TextField(blank=True, null=True)),
                ('ipl', models.TextField(blank=True, null=True)),
                ('console', models.IntegerField(blank=True, null=True)),
                ('board', models.TextField(blank=True, null=True)),
                ('for_sale', models.IntegerField(blank=True, null=True)),
                ('extra_imgs', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('creatorjob', models.CharField(blank=True, db_column='creatorJob', max_length=50, null=True)),
                ('blip', models.TextField(blank=True, null=True)),
                ('upgrades', models.TextField(blank=True, null=True)),
                ('apartmentcount', models.IntegerField(blank=True, db_column='apartmentCount', null=True)),
                ('creatorgotmoney', models.IntegerField(db_column='creatorGotMoney')),
            ],
            options={
                'db_table': 'houselocations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HouseObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('coords', models.TextField()),
                ('house', models.CharField(blank=True, max_length=80, null=True)),
                ('construction', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'house_objects',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HousePlants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(blank=True, max_length=50, null=True)),
                ('stage', models.CharField(blank=True, max_length=50, null=True)),
                ('sort', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=50, null=True)),
                ('food', models.IntegerField(blank=True, null=True)),
                ('health', models.IntegerField(blank=True, null=True)),
                ('progress', models.IntegerField(blank=True, null=True)),
                ('coords', models.TextField(blank=True, null=True)),
                ('plantid', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'house_plants',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HouseRents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(max_length=50)),
                ('identifier', models.CharField(max_length=80)),
                ('payed', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'house_rents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
                ('rare', models.IntegerField()),
                ('can_remove', models.IntegerField()),
            ],
            options={
                'db_table': 'items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobGrades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('skin_male', models.TextField()),
                ('skin_female', models.TextField()),
            ],
            options={
                'db_table': 'job_grades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(max_length=50)),
                ('whitelisted', models.IntegerField()),
            ],
            options={
                'db_table': 'jobs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KavesMechanics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate', models.TextField(blank=True, null=True)),
                ('data', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'kaves_mechanics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Licenses',
            fields=[
                ('type', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'licenses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManagementOutfits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('minrank', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('props', models.CharField(blank=True, max_length=1000, null=True)),
                ('components', models.CharField(blank=True, max_length=1500, null=True)),
            ],
            options={
                'db_table': 'management_outfits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MechanicData',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('balance', models.FloatField()),
                ('owner_id', models.CharField(blank=True, max_length=255, null=True)),
                ('owner_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'mechanic_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MechanicEmployees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('mechanic', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=100)),
                ('joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'mechanic_employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MechanicInvoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=255, null=True)),
                ('mechanic', models.CharField(max_length=255)),
                ('total', models.FloatField()),
                ('data', models.TextField()),
                ('paid', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'mechanic_invoices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MechanicOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('mechanic', models.CharField(max_length=255)),
                ('plate', models.CharField(max_length=10)),
                ('amount_paid', models.FloatField()),
                ('cart', models.TextField()),
                ('props_to_apply', models.TextField()),
                ('installation_progress', models.TextField(blank=True, null=True)),
                ('fulfilled', models.IntegerField(blank=True, null=True)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'mechanic_orders',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MechanicServicingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=255)),
                ('mechanic', models.CharField(max_length=255)),
                ('plate', models.CharField(max_length=10)),
                ('serviced_part', models.CharField(max_length=10)),
                ('mileage_km', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'mechanic_servicing_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MechanicSettings',
            fields=[
                ('identifier', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('preferences', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mechanic_settings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MechanicVehicledata',
            fields=[
                ('plate', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('data', models.TextField()),
            ],
            options={
                'db_table': 'mechanic_vehicledata',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MulticharacterSlots',
            fields=[
                ('identifier', models.CharField(max_length=46, primary_key=True, serialize=False)),
                ('slots', models.IntegerField()),
            ],
            options={
                'db_table': 'multicharacter_slots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OwnedVehicles',
            fields=[
                ('owner', models.CharField(blank=True, max_length=46, null=True)),
                ('plate', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('vehicle', models.TextField(blank=True, null=True)),
                ('type', models.CharField(max_length=20)),
                ('job', models.CharField(blank=True, max_length=20, null=True)),
                ('stored', models.IntegerField()),
                ('parking', models.CharField(blank=True, max_length=60, null=True)),
                ('pound', models.CharField(blank=True, max_length=60, null=True)),
                ('mileage', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'owned_vehicles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneBackups',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'phone_backups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneClockAlarms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hours', models.IntegerField()),
                ('minutes', models.IntegerField()),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('enabled', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'phone_clock_alarms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneCrypto',
            fields=[
                ('pk', models.CompositePrimaryKey('id', 'coin', blank=True, editable=False, primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=100)),
                ('coin', models.CharField(max_length=15)),
                ('amount', models.FloatField()),
                ('invested', models.IntegerField()),
            ],
            options={
                'db_table': 'phone_crypto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneDarkchatAccounts',
            fields=[
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'phone_darkchat_accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneDarkchatChannels',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'phone_darkchat_channels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneDarkchatMembers',
            fields=[
                ('pk', models.CompositePrimaryKey('channel_name', 'username', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'phone_darkchat_members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneDarkchatMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_darkchat_messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneInstagramAccounts',
            fields=[
                ('display_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('profile_image', models.CharField(blank=True, max_length=500, null=True)),
                ('bio', models.CharField(blank=True, max_length=100, null=True)),
                ('post_count', models.IntegerField()),
                ('story_count', models.IntegerField()),
                ('follower_count', models.IntegerField()),
                ('following_count', models.IntegerField()),
                ('private', models.IntegerField(blank=True, null=True)),
                ('verified', models.IntegerField(blank=True, null=True)),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_instagram_accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneInstagramComments',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=500)),
                ('like_count', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_instagram_comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneInstagramFollowRequests',
            fields=[
                ('pk', models.CompositePrimaryKey('requester', 'requestee', blank=True, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_instagram_follow_requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneInstagramFollows',
            fields=[
                ('pk', models.CompositePrimaryKey('followed', 'follower', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'phone_instagram_follows',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneInstagramLikes',
            fields=[
                ('pk', models.CompositePrimaryKey('id', 'username', blank=True, editable=False, primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=10)),
                ('is_comment', models.IntegerField()),
            ],
            options={
                'db_table': 'phone_instagram_likes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneInstagramMessages',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('attachments', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_instagram_messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneInstagramNotifications',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('post_id', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_instagram_notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneInstagramPosts',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('media', models.TextField(blank=True, null=True)),
                ('caption', models.CharField(max_length=500)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('like_count', models.IntegerField()),
                ('comment_count', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_instagram_posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneInstagramStories',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=500)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_instagram_stories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneInstagramStoriesViews',
            fields=[
                ('pk', models.CompositePrimaryKey('story_id', 'viewer', blank=True, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_instagram_stories_views',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneLastPhone',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'phone_last_phone',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneLoggedInAccounts',
            fields=[
                ('pk', models.CompositePrimaryKey('phone_number', 'app', 'username', blank=True, editable=False, primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('active', models.IntegerField()),
            ],
            options={
                'db_table': 'phone_logged_in_accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneMailAccounts',
            fields=[
                ('address', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'phone_mail_accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneMailDeleted',
            fields=[
                ('pk', models.CompositePrimaryKey('message_id', 'address', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'phone_mail_deleted',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneMailMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(max_length=100)),
                ('sender', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('attachments', models.TextField(blank=True, null=True)),
                ('actions', models.TextField(blank=True, null=True)),
                ('read', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_mail_messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneMapsLocations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('x_pos', models.FloatField()),
                ('y_pos', models.FloatField()),
            ],
            options={
                'db_table': 'phone_maps_locations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneMarketplacePosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('attachments', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_marketplace_posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneMessageChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_group', models.IntegerField()),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_message', models.CharField(max_length=50)),
                ('last_message_timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_message_channels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneMessageMembers',
            fields=[
                ('pk', models.CompositePrimaryKey('channel_id', 'phone_number', blank=True, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_owner', models.IntegerField()),
                ('deleted', models.IntegerField()),
                ('unread', models.IntegerField()),
            ],
            options={
                'db_table': 'phone_message_members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneMessageMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=15)),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('attachments', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_message_messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneMusicPlaylists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cover', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'phone_music_playlists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneMusicSavedPlaylists',
            fields=[
                ('pk', models.CompositePrimaryKey('playlist_id', 'phone_number', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'phone_music_saved_playlists',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneMusicSongs',
            fields=[
                ('pk', models.CompositePrimaryKey('song_id', 'playlist_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('song_id', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'phone_music_songs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_notes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=50)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('thumbnail', models.CharField(blank=True, max_length=500, null=True)),
                ('avatar', models.CharField(blank=True, max_length=500, null=True)),
                ('show_avatar', models.IntegerField(blank=True, null=True)),
                ('custom_data', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhonePhoneBlockedNumbers',
            fields=[
                ('pk', models.CompositePrimaryKey('phone_number', 'blocked_number', blank=True, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15)),
                ('blocked_number', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'phone_phone_blocked_numbers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhonePhoneCalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller', models.CharField(max_length=15)),
                ('callee', models.CharField(max_length=15)),
                ('duration', models.IntegerField()),
                ('answered', models.IntegerField(blank=True, null=True)),
                ('hide_caller_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_phone_calls',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhonePhoneContacts',
            fields=[
                ('pk', models.CompositePrimaryKey('contact_phone_number', 'phone_number', blank=True, editable=False, primary_key=True, serialize=False)),
                ('contact_phone_number', models.CharField(max_length=15)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('profile_image', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('favourite', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'phone_phone_contacts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhonePhones',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('pin', models.CharField(blank=True, max_length=4, null=True)),
                ('face_id', models.CharField(blank=True, max_length=100, null=True)),
                ('settings', models.TextField(blank=True, null=True)),
                ('is_setup', models.IntegerField(blank=True, null=True)),
                ('assigned', models.IntegerField(blank=True, null=True)),
                ('battery', models.IntegerField()),
                ('last_seen', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_phones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhonePhoneVoicemail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller', models.CharField(max_length=15)),
                ('callee', models.CharField(max_length=15)),
                ('url', models.CharField(max_length=500)),
                ('duration', models.IntegerField()),
                ('hide_caller_id', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_phone_voicemail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhonePhotoAlbumMembers',
            fields=[
                ('pk', models.CompositePrimaryKey('album_id', 'phone_number', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'phone_photo_album_members',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhonePhotoAlbumPhotos',
            fields=[
                ('pk', models.CompositePrimaryKey('album_id', 'photo_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'phone_photo_album_photos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhonePhotoAlbums',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('shared', models.IntegerField()),
            ],
            options={
                'db_table': 'phone_photo_albums',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhonePhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=500)),
                ('is_video', models.IntegerField(blank=True, null=True)),
                ('size', models.FloatField()),
                ('metadata', models.CharField(blank=True, max_length=20, null=True)),
                ('is_favourite', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_photos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneServicesChannels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('company', models.CharField(max_length=50)),
                ('last_message', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_services_channels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneServicesMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=1000)),
                ('x_pos', models.IntegerField(blank=True, null=True)),
                ('y_pos', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_services_messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneTiktokAccounts',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('bio', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar', models.CharField(blank=True, max_length=500, null=True)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('verified', models.IntegerField(blank=True, null=True)),
                ('follower_count', models.IntegerField()),
                ('following_count', models.IntegerField()),
                ('like_count', models.IntegerField()),
                ('video_count', models.IntegerField()),
                ('twitter', models.CharField(blank=True, max_length=20, null=True)),
                ('instagram', models.CharField(blank=True, max_length=20, null=True)),
                ('show_likes', models.IntegerField(blank=True, null=True)),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_tiktok_accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneTiktokChannels',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('last_message', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_tiktok_channels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneTiktokComments',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=550)),
                ('likes', models.IntegerField()),
                ('replies', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_tiktok_comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneTiktokCommentsLikes',
            fields=[
                ('pk', models.CompositePrimaryKey('username', 'comment_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'phone_tiktok_comments_likes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneTiktokFollows',
            fields=[
                ('pk', models.CompositePrimaryKey('followed', 'follower', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'phone_tiktok_follows',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneTiktokLikes',
            fields=[
                ('pk', models.CompositePrimaryKey('username', 'video_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'phone_tiktok_likes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneTiktokMessages',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=500)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_tiktok_messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneTiktokNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_tiktok_notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneTiktokPinnedVideos',
            fields=[
                ('pk', models.CompositePrimaryKey('username', 'video_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'phone_tiktok_pinned_videos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneTiktokSaves',
            fields=[
                ('pk', models.CompositePrimaryKey('username', 'video_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'phone_tiktok_saves',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneTiktokUnreadMessages',
            fields=[
                ('pk', models.CompositePrimaryKey('username', 'channel_id', blank=True, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'phone_tiktok_unread_messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneTiktokVideos',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('src', models.CharField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=100, null=True)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('music', models.TextField(blank=True, null=True)),
                ('likes', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('views', models.IntegerField()),
                ('saves', models.IntegerField()),
                ('pinned_comment', models.CharField(blank=True, max_length=10, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_tiktok_videos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneTiktokViews',
            fields=[
                ('pk', models.CompositePrimaryKey('username', 'video_id', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'phone_tiktok_views',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneTinderMatches',
            fields=[
                ('pk', models.CompositePrimaryKey('phone_number_1', 'phone_number_2', blank=True, editable=False, primary_key=True, serialize=False)),
                ('latest_message', models.CharField(blank=True, max_length=1000, null=True)),
                ('latest_message_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'phone_tinder_matches',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneTinderMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('attachments', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_tinder_messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneTinderSwipes',
            fields=[
                ('pk', models.CompositePrimaryKey('swiper', 'swipee', blank=True, editable=False, primary_key=True, serialize=False)),
                ('liked', models.IntegerField()),
            ],
            options={
                'db_table': 'phone_tinder_swipes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneTwitterAccounts',
            fields=[
                ('display_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('bio', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_image', models.CharField(blank=True, max_length=500, null=True)),
                ('profile_header', models.CharField(blank=True, max_length=500, null=True)),
                ('pinned_tweet', models.CharField(blank=True, max_length=50, null=True)),
                ('verified', models.IntegerField(blank=True, null=True)),
                ('follower_count', models.IntegerField()),
                ('following_count', models.IntegerField()),
                ('private', models.IntegerField(blank=True, null=True)),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_twitter_accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneTwitterFollowRequests',
            fields=[
                ('pk', models.CompositePrimaryKey('requester', 'requestee', blank=True, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_twitter_follow_requests',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneTwitterFollows',
            fields=[
                ('pk', models.CompositePrimaryKey('followed', 'follower', blank=True, editable=False, primary_key=True, serialize=False)),
                ('notifications', models.IntegerField()),
            ],
            options={
                'db_table': 'phone_twitter_follows',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneTwitterHashtags',
            fields=[
                ('hashtag', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('last_used', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_twitter_hashtags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneTwitterLikes',
            fields=[
                ('pk', models.CompositePrimaryKey('tweet_id', 'username', blank=True, editable=False, primary_key=True, serialize=False)),
                ('tweet_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_twitter_likes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneTwitterMessages',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=1000, null=True)),
                ('attachments', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_twitter_messages',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneTwitterNotifications',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('tweet_id', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_twitter_notifications',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneTwitterTweets',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=280, null=True)),
                ('attachments', models.TextField(blank=True, null=True)),
                ('reply_to', models.CharField(blank=True, max_length=50, null=True)),
                ('like_count', models.IntegerField(blank=True, null=True)),
                ('reply_count', models.IntegerField(blank=True, null=True)),
                ('retweet_count', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_twitter_tweets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneTwitterRetweets',
            fields=[
                ('pk', models.CompositePrimaryKey('tweet_id', 'username', blank=True, editable=False, primary_key=True, serialize=False)),
                ('tweet_id', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_twitter_retweets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneVoiceMemosRecordings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=50)),
                ('file_url', models.CharField(max_length=500)),
                ('file_length', models.IntegerField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_voice_memos_recordings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneWalletTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('company', models.CharField(max_length=50)),
                ('logo', models.CharField(blank=True, max_length=200, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_wallet_transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneYellowPagesPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('attachment', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_yellow_pages_posts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerHouses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house', models.CharField(blank=True, max_length=50, null=True)),
                ('citizenid', models.CharField(blank=True, max_length=50, null=True)),
                ('owner', models.CharField(blank=True, max_length=46, null=True)),
                ('keyholders', models.TextField(blank=True, null=True)),
                ('stash', models.TextField(blank=True, null=True)),
                ('outfit', models.TextField(blank=True, null=True)),
                ('logout', models.TextField(blank=True, null=True)),
                ('decoratestash', models.TextField(blank=True, db_column='decorateStash', null=True)),
                ('charge', models.TextField(blank=True, null=True)),
                ('credit', models.CharField(blank=True, max_length=50, null=True)),
                ('creditprice', models.CharField(blank=True, db_column='creditPrice', max_length=50, null=True)),
                ('console', models.TextField(blank=True, null=True)),
                ('decoratecoords', models.TextField(blank=True, db_column='decorateCoords', null=True)),
                ('rented', models.IntegerField(blank=True, null=True)),
                ('rentprice', models.IntegerField(blank=True, db_column='rentPrice', null=True)),
                ('rentable', models.IntegerField(blank=True, null=True)),
                ('purchasable', models.IntegerField(blank=True, null=True)),
                ('vaultcodes', models.TextField(blank=True, db_column='vaultCodes', null=True)),
            ],
            options={
                'db_table': 'player_houses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerOutfitCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outfitid', models.IntegerField()),
                ('code', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'player_outfit_codes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerOutfits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenid', models.CharField(blank=True, max_length=50, null=True)),
                ('outfitname', models.CharField(max_length=50)),
                ('model', models.CharField(blank=True, max_length=50, null=True)),
                ('props', models.CharField(blank=True, max_length=1000, null=True)),
                ('components', models.CharField(blank=True, max_length=1500, null=True)),
            ],
            options={
                'db_table': 'player_outfits',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Playerskins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenid', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('skin', models.TextField()),
                ('active', models.IntegerField()),
            ],
            options={
                'db_table': 'playerskins',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RacerNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenid', models.TextField()),
                ('racername', models.TextField()),
                ('lasttouched', models.DateTimeField()),
                ('races', models.IntegerField()),
                ('wins', models.IntegerField()),
                ('tracks', models.IntegerField()),
                ('auth', models.CharField(blank=True, max_length=50, null=True)),
                ('crew', models.CharField(blank=True, max_length=50, null=True)),
                ('createdby', models.CharField(blank=True, max_length=50, null=True)),
                ('revoked', models.IntegerField(blank=True, null=True)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('active', models.IntegerField()),
                ('crypto', models.IntegerField()),
            ],
            options={
                'db_table': 'racer_names',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RaceTracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('checkpoints', models.TextField(blank=True, null=True)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('creatorid', models.CharField(blank=True, max_length=50, null=True)),
                ('creatorname', models.CharField(blank=True, max_length=50, null=True)),
                ('distance', models.IntegerField(blank=True, null=True)),
                ('raceid', models.CharField(blank=True, max_length=50, null=True)),
                ('access', models.TextField(blank=True, null=True)),
                ('curated', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'race_tracks',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RacingCrews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_name', models.TextField(blank=True, null=True)),
                ('members', models.JSONField(blank=True, null=True)),
                ('wins', models.IntegerField(blank=True, null=True)),
                ('races', models.IntegerField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
                ('founder_name', models.TextField(blank=True, null=True)),
                ('founder_citizenid', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'racing_crews',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RacingRaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raceid', models.CharField(db_column='raceId', max_length=255)),
                ('trackid', models.CharField(db_column='trackId', max_length=255)),
                ('results', models.JSONField(blank=True, null=True)),
                ('amountofracers', models.IntegerField(db_column='amountOfRacers')),
                ('laps', models.IntegerField()),
                ('hostname', models.CharField(blank=True, db_column='hostName', max_length=255, null=True)),
                ('maxclass', models.CharField(blank=True, db_column='maxClass', max_length=50, null=True)),
                ('ghosting', models.IntegerField()),
                ('ranked', models.IntegerField()),
                ('reversed', models.IntegerField()),
                ('firstperson', models.IntegerField(db_column='firstPerson')),
                ('automated', models.IntegerField()),
                ('hidden', models.IntegerField()),
                ('silent', models.IntegerField()),
                ('buyin', models.IntegerField(db_column='buyIn')),
                ('data', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'racing_races',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RealVehicleshop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('information', models.TextField(blank=True, null=True)),
                ('vehicles', models.TextField(blank=True, null=True)),
                ('categories', models.TextField(blank=True, null=True)),
                ('feedbacks', models.TextField(blank=True, null=True)),
                ('complaints', models.TextField(blank=True, null=True)),
                ('preorders', models.TextField(blank=True, null=True)),
                ('employees', models.TextField(blank=True, null=True)),
                ('soldvehicles', models.TextField(blank=True, null=True)),
                ('transactions', models.TextField(blank=True, null=True)),
                ('perms', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'real_vehicleshop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RentedVehicles',
            fields=[
                ('vehicle', models.CharField(max_length=60)),
                ('plate', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=255)),
                ('base_price', models.IntegerField()),
                ('rent_price', models.IntegerField()),
                ('owner', models.CharField(blank=True, max_length=46, null=True)),
            ],
            options={
                'db_table': 'rented_vehicles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SocietyMoneywash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=46, null=True)),
                ('society', models.CharField(max_length=60)),
                ('amount', models.IntegerField()),
            ],
            options={
                'db_table': 'society_moneywash',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TrackTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackid', models.CharField(db_column='trackId', max_length=255)),
                ('racername', models.CharField(db_column='racerName', max_length=255)),
                ('carclass', models.CharField(db_column='carClass', max_length=50)),
                ('vehiclemodel', models.CharField(db_column='vehicleModel', max_length=255)),
                ('racetype', models.CharField(db_column='raceType', max_length=50)),
                ('time', models.IntegerField()),
                ('reversed', models.IntegerField()),
                ('pbhistory', models.JSONField(blank=True, db_column='pbHistory', null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'track_times',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserLicenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60)),
                ('owner', models.CharField(blank=True, max_length=46, null=True)),
            ],
            options={
                'db_table': 'user_licenses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('identifier', models.CharField(max_length=46, unique=True)),
                ('ssn', models.CharField(max_length=11, unique=True)),
                ('accounts', models.TextField(blank=True, null=True)),
                ('group', models.CharField(blank=True, max_length=50, null=True)),
                ('inventory', models.TextField(blank=True, null=True)),
                ('job', models.CharField(blank=True, max_length=20, null=True)),
                ('job_grade', models.IntegerField(blank=True, null=True)),
                ('loadout', models.TextField(blank=True, null=True)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('position', models.TextField(blank=True, null=True)),
                ('firstname', models.CharField(blank=True, max_length=16, null=True)),
                ('lastname', models.CharField(blank=True, max_length=16, null=True)),
                ('dateofbirth', models.CharField(blank=True, max_length=10, null=True)),
                ('sex', models.CharField(blank=True, max_length=1, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('skin', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('is_dead', models.IntegerField(blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disabled', models.IntegerField(blank=True, null=True)),
                ('last_property', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('playtime', models.IntegerField(blank=True, null=True)),
                ('inside', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleCategories',
            fields=[
                ('name', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'vehicle_categories',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('category', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'db_table': 'vehicles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VehicleSold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('plate', models.CharField(max_length=50)),
                ('soldby', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'vehicle_sold',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Whitelist',
            fields=[
                ('identifier', models.CharField(max_length=46, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'whitelist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneTinderAccounts',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.OneToOneField(db_column='phone_number', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.phonephones')),
                ('photos', models.TextField(blank=True, null=True)),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('dob', models.DateField()),
                ('is_male', models.IntegerField()),
                ('interested_men', models.IntegerField()),
                ('interested_women', models.IntegerField()),
                ('active', models.IntegerField()),
                ('last_seen', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_tinder_accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneTwitterPromoted',
            fields=[
                ('tweet', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.phonetwittertweets')),
                ('promotions', models.IntegerField()),
                ('views', models.IntegerField()),
            ],
            options={
                'db_table': 'phone_twitter_promoted',
                'managed': False,
            },
        ),
    ]
